name: Generate Data Clumps Badge
description: Create badge from data-clumps-doctor report
inputs:
  directory:
    description: Path to directory containing data-clumps.json (and where badge will be stored)
    required: true
runs:
  using: "composite"
  steps:
    - name: Prepare badge directory
      shell: bash
      run: mkdir -p "${{ inputs.directory }}/badges"
    - name: Extract data clumps count
      id: data-clumps-count
      shell: bash
      run: |
        echo "count=$(jq '.report_summary.amount_data_clumps' \"${{ inputs.directory }}/data-clumps.json\")" >> "$GITHUB_OUTPUT"
    - name: Determine badge color
      id: badge-color
      shell: bash
      run: |
        count="${{ steps.data-clumps-count.outputs.count }}"
        if [ "$count" -le 10 ]; then
          echo "color=08A008" >> "$GITHUB_OUTPUT"
        elif [ "$count" -le 100 ]; then
          echo "color=FE7D37" >> "$GITHUB_OUTPUT"
        else
          echo "color=F85149" >> "$GITHUB_OUTPUT"
        fi
    - name: Generate badge
      uses: emibcn/badge-action@v2.0.2
      with:
        label: data clumps
        status: ${{ steps.data-clumps-count.outputs.count }}
        color: ${{ steps.badge-color.outputs.color }}
        path: "${{ inputs.directory }}/badges/data-clumps.svg"
